import {
    ESFJ, 
    ISFJ, 
    ENTP, 
    INTP, 
    ESTP, 
    ISTP, 
    ENFJ, 
    INFJ, 
    ESFP, 
    ISFP, 
    ENTJ, 
    INTJ, 
    ENFP, 
    INFP, 
    ESTJ, 
    ISTJ,
    customcomedy,
    contact,
    github,
    javascript,
    linkedin,
    solarutopia,
    hearthenergy,
    react,
    souptaco,
    tailwindcss,
    suunstar,
    unity,
    bambulab,
    solidity,
    python,
    csharp
} from "../assets/icons";

export const skills = [
    {
        imageUrl: unity,
        name: "unity",
        type: "unity",
    },
    {
        imageUrl: bambulab,
        name: "bambulab",
        type: "bambulab",
    },
    {
        imageUrl: solidity,
        name: "solidity",
        type: "solidity",
    },
    {
        imageUrl: github,
        name: "GitHub",
        type: "Version Control",
    },
    {
        imageUrl: javascript,
        name: "JavaScript",
        type: "Frontend",
    },
    {
        imageUrl: react,
        name: "React",
        type: "Frontend",
    },
    {
        imageUrl: tailwindcss,
        name: "Tailwind CSS",
        type: "Frontend",
    },
    {
      imageUrl: python,
      name: "python",
      type: "python",
  },
  {
    imageUrl: csharp,
    name: "csharp",
    type: "csharp",
}
];

export const experiences = [
    {
        title: "ENTJ",
        company_name: "SOCIONICS-WAYFARER-1",
        icon: ENTJ,
        iconBg: "#E6DEDD",
        date: "ENTJ",
        points: [
          "[ Ego: Te-Hero, Ni-Parent, Se-Child, Fi-Inferior ]",
          "[ Unconscious: Ti-Nemesis, Ne-Critic, Si-Trickster, Fe-Demon ]",
          "[ Subconscious: Fi-Morals, Se-Physics, Ni-Willpower, Te-Rationale ]",
          "[ Superego: Fe-Ethics, Si-Discipline, Ne-Metaphysics, Ti-Logic ]",
        ],
      },
      {
        title: "INTP",
        company_name: "SOCIONICS-CRUSADER-2",
        icon: INTP,
        iconBg: "#E6DEDD",
        date: "INTP",
        points: [
          "[ Ego: Ti-Hero, Ne-Parent, Si-Child, Fe-Inferior ]",
          "[ Unconscious: Te-Nemesis, Ni-Critic, Se-Trickster, Fi-Demon ]",
          "[ Subconscious: Fe-Ethics, Si-Discipline, Ne-Metaphysics, Ti-Logic ]",
          "[ Superego: Fi-Morals, Se-Physics, Ni-Willpower, Te-Rationale ]",
        ],
      },
      {
        title: "ESFJ",
        company_name: "SOCIONICS-CRUSADER-3",
        icon: ESFJ,
        iconBg: "#E6DEDD",
        date: "ESFJ",
        points: [
          "[ Ego: Fe-Hero, Si-Parent, Ne-Child, Ti-Inferior ]",
          "[ Unconscious: Fi-Nemisis, Se-Critic, Ni-Trickster, Te-Demon ]",
          "[ Subconscious: Ti-Logic, Ne-Metaphysics, Si-Discipline, Fe-Ethics ]",
          "[ Superego: Te-Rationale, Ni-Willpower, Se-Physics, Fi-Morals ]",
        ],
      },
      {
        title: "ISFP",
        company_name: "SOCIONICS-WAYFARER-4",
        icon: ISFP,
        iconBg: "#E6DEDD",
        date: "ISFP",
        points: [
          "[ Ego: Fi-Hero, Se-Parent, Ni-Child, Te-Inferior ]",
          "[ Unconscious: Fe-Nemesis, Si-Critic, Ne-Trickster, Ti-Demon ]",
          "[ Subconscious: Te-Rationale, Ni-Willpower, Se-Physics, Fi-Morals ]",
          "[ Superego: Ti-Logic, Ne-Metaphysics, Si-Discipline, Fe-Ethics ]",
        ],
      },
      {
        title: "ESFP",
        company_name: "SOCIONICS-WAYFARER-5",
        icon: ESFP,
        iconBg: "#E6DEDD",
        date: "ESFP",
        points: [
          "[ Ego: Se-Hero, Fi-Parent, Te-Child, Ni-Inferior ]",
          "[ Unconscious: Si-Nemesis, Fe-Critic, Ti-Trickster, Ne-Demon ]",
          "[ Subconscious: Ni-Willpower, Te-Rationale, Fi-Morals, Se-Physics ]",
          "[ Superego: Ne-Metaphysics, Ti-Logic, Fe-Ethics, Si-Discipline ]",
        ],
      },
      {
        title: "ISFJ",
        company_name: "SOCIONICS-CRUSADER-6",
        icon: ISFJ,
        iconBg: "#E6DEDD",
        date: "ISFJ",
        points: [
          "[ Ego: Si-Hero, Fe-Parent, Ti-Child, Ne-Inferior ]",
          "[ Unconscious: Se-Nemesis, Fi-Critic, Te-Trickster, Ni-Demon ]",
          "[ Subconscious: Ne-Physics, Ti-Logic, Fe-Ethics, Si-Discipline ]",
          "[ Superego: Ni-Willpower, Te-Rationale, Fi-Morals, Se-Physics ]",
        ],
      },
      {
        title: "ENTP",
        company_name: "SOCIONICS-CRUSADER-7",
        icon: ENTP,
        iconBg: "#E6DEDD",
        date: "ENTP",
        points: [
          "[ Ego: Ne-Hero, Ti-Parent, Fe-Child, Si-Inferior ]",
          "[ Unconscious: Ni-Nemesis, Te-Critic, Fi-Trickster, Se-Demon ]",
          "[ Subconscious: Si-Discipline, Fe-Ethics, Ti-Logic, Ne-Metaphysics ]",
          "[ Superego: Se-Physics, Fi-Morals, Te-Rationale, Ni-Willpower ]",
        ],
      },
      {
        title: "INTJ",
        company_name: "SOCIONICS-WAYFARER-8",
        icon: INTJ,
        iconBg: "#E6DEDD",
        date: "INTJ",
        points: [
          "[ Ego: Ni-Hero, Te-Parent, Fi-Child, Se-Inferior ]",
          "[ Unconscious: Ne-Nemesis, Ti-Critic, Fe-Trickster, Si-Demon ]",
          "[ Subconscious: Se-Physics, Fi-Morals, Te-Rationale, Ni-Willpower ]",
          "[ Superego: Si-Discipline, Fe-Ethics, Ti-Logic, Ne-Metaphysics ]",
        ],
      },
      {
        title: "ESTP",
        company_name: "SOCIONICS-TEMPLAR-9",
        icon: ESTP,
        iconBg: "#E6DEDD",
        date: "ESTP",
        points: [
          "[ Ego: Se-Hero, Ti-Parent, Fe-Child, Ni-Inferior ]",
          "[ Unconscious: Si-Nemesis, Te-Critic, Fi-Trickster, Ne-Demon ]",
          "[ Subconscious: Ni-Willpower, Fe-Ethics, Ti-Logic, Se-Physics ]",
          "[ Superego: Ne-Metaphysics, Fi-Morals, Te-Rationale, Si-Discipline ]",
        ],
      },
      {
        title: "ISTJ",
        company_name: "SOCIONICS-PHILOSOPHER-10",
        icon: ISTJ,
        iconBg: "#E6DEDD",
        date: "ISTJ",
        points: [
          "[ Ego: Si-Hero, Te-Parent, Fi-Child, Ne-Inferior ]",
          "[ Unconscious: Se-Nemesis, Ti-Critic, Fe-Trickster, Ni-Demon ]",
          "[ Subconscious: Ne-Metaphysics, Fi-Morals, Te-Rationale, Si-Discipline ]",
          "[ Superego: Ni-Willpower, Fe-Ethics, Ti-Logic, Se-Physics ]",
        ],
      },
      {
        title: "ESTJ",
        company_name: "SOCIONICS-PHILOSOPHER-11",
        icon: ESTJ,
        iconBg: "#E6DEDD",
        date: "ESTJ",
        points: [
          "[ Ego: Te-Hero, Si-Parent, Ne-Child, Fi-Inferior ]",
          "[ Unconscious: Ti-Nemesis, Se-Critic, Ni-Trickster, Fe-Demon ]",
          "[ Subconscious: Fi-Morals, Ne-Metaphysics, Si-Discipline, Te-Rationale ]",
          "[ Superego: Fe-Ethics, Ni-Willpower, Se-Physics, Ti-Logic ]",
        ],
      },
      {
        title: "ISTP",
        company_name: "SOCIONICS-TEMPLAR-12",
        icon: ISTP,
        iconBg: "#E6DEDD",
        date: "ISTP",
        points: [
          "[ Ego: Ti-Hero, Se-Parent, Ni-Child, Fe-Inferior ]",
          "[ Unconscious: Te-Nemesis, Si-Critic, Ne-Trickster, Fi-Demon ]",
          "[ Subconscious: Fe-Ethics, Ni-Willpower, Se-Physics, Ti-Logic ]",
          "[ Superego: Fi-Morals, Ne-Metaphysics, Si-Discipline, Te-Rationale ]",
        ],
      },
      {
        title: "ENFJ",
        company_name: "SOCIONICS-TEMPLAR-13",
        icon: ENFJ,
        iconBg: "#E6DEDD",
        date: "ENFJ",
        points: [
          "[ Ego: Fe-Hero, Ni-Parent, Se-Child, Ti-Inferior ]",
          "[ Unconscious: Fi-Nemesis, Ne-Critic, Si-Trickster, Te-Demon ]",
          "[ Subconscious: Ti-Logic, Se-Physics, Ni-Willpower, Fe-Ethics ]",
          "[ Superego: Te-Rationale, Si-Discipline, Ne-Metaphysics, Fi-Morals ]",
        ],
      },
      {
        title: "INFP",
        company_name: "SOCIONICS-PHILOSOPHER-14",
        icon: INFP,
        iconBg: "#E6DEDD",
        date: "INFP",
        points: [
          "[ Ego: Fi-Hero, Ne-Parent, Si-Child, Te-Inferior ]",
          "[ Unconscious: Fe-Nemesis, Ni-Critic, Se-Trickster, Ti-Demon ]",
          "[ Subconscious: Te-Rationale, Si-Discipline, Ne-Metaphysics, Fi-Morals ]",
          "[ Superego: Ti-Logic, Se-Physics, Ni-Willpower, Fe-Ethics ]",
        ],
      },
      {
        title: "ENFP",
        company_name: "SOCIONICS-PHILOSOPHER-15",
        icon: ENFP,
        iconBg: "#E6DEDD",
        date: "ENFP",
        points: [
          "[ Ego: Ne-Hero, Fi-Parent, Te-Child, Si-Inferior ]",
          "[ Unconscious: Ni-Nemesis, Fe-Critic, Ti-Trickster, Se-Demon ]",
          "[ Subconscious: Si-Discipline, Te-Rationale, Fi-Morals, Ne-Metaphysics ]",
          "[ Superego: Se-Physics, Ti-Logic, Fe-Ethics, Ni-Willpower ]",
        ],
      },
      {
        title: "INFJ",
        company_name: "SOCIONICS-TEMPLAR-16",
        icon: INFJ,
        iconBg: "#E6DEDD",
        date: "INFJ",
        points: [
          "[ Ego: Ni-Hero, Fe-Parent, Ti-Child, Se-Inferior ]",
          "[ Unconscious: Ne-Nemesis, Fi-Critic, Te-Trickster, Si-Demon ]",
          "[ Subconscious: Se-Physics, Ti-Logic, Fe-Ethics, Ni-Willpower ]",
          "[ Superego: Si-Discipline, Te-Rationale, Fi-Morals, Ne-Metaphysics ]",
        ],
      },
    ];

export const socialLinks = [
    {
        name: 'Contact',
        iconUrl: contact,
        link: '/contact',
    },
    {
        name: 'GitHub',
        iconUrl: github,
        link: 'https://github.com/PortraitstoneLabs/portraitstonelabs',
    },
    {
        name: 'LinkedIn',
        iconUrl: linkedin,
        link: 'https://www.linkedin.com/company/portraitstonelabs/',
    },
];

export const projects = [
    {
        iconUrl: customcomedy,
        theme: 'btn-back-green',
        name: 'Custom Comedy Corporation',
        description: 'A comedy research & development firm',
        link: 'https://customcomedy.org',
    },
    {
        iconUrl: hearthenergy,
        theme: 'btn-back-yellow',
        name: 'Hearth Energy',
        description: 'Auditing the residential & commercial solar industry',
        link: 'https://hearthenergy.org/',
    },
];